---
name: Check Flakes
on:   
  pull_request:
    branches:
      - main

env:
  OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
  OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}

jobs:
  check_flakes:
    runs-on: ubuntu-latest
    steps:
      - uses: 1password/load-secrets-action/configure@13f58eec611f8e5db52ec16247f58c508398f3e6  # v3
        with:
          connect-host: ${{ env.OP_CONNECT_HOST }}
          connect-token: ${{ env.OP_CONNECT_TOKEN }}

      - uses: 1password/load-secrets-action@13f58eec611f8e5db52ec16247f58c508398f3e6  # v3
        with:
          export-env: true
        env:
          BOT_APP_ID: op://homelab/GITHUB/GITHUB_APP_ID
          BOT_APP_PRIVATE_KEY: op://homelab/GITHUB/GITHUB_APP_PRIVATE_KEY

      - name: Generate Token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42  # v2.1.4
        id: app-token
        with:
          app-id: "${{ env.BOT_APP_ID }}"
          private-key: "${{ env.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - uses: cachix/install-nix-action@fd24c48048070c1be9acd18c9d369a83f0fe94d7  # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix flake check
